### ISSUE TITLE
Broken with Foundry v7.10

### ISSUE THREAD

**Issue by Kylarfi** [sfuqua/fvtt-hidden-initiative#12]
With the new update it seems to have broke and doesn't allow rolling of initiative.

createRollInitiativeReplacement.js:14 Uncaught (in promise) TypeError: this.combatants.get is not a function
    at Combat.getCombatantById (createRollInitiativeReplacement.js:14)
    at Combat.partitionRolls (createRollInitiativeReplacement.js:25)
    at Combat.rollInitiative (createRollInitiativeReplacement.js:65)
    at HiddenInitiativeMixinClass._onCombatantControl (foundry.js:26588)
    at HTMLAnchorElement.<anonymous> (foundry.js:26479)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
getCombatantById @ createRollInitiativeReplacement.js:14
partitionRolls @ createRollInitiativeReplacement.js:25
rollInitiative @ createRollInitiativeReplacement.js:65
_onCombatantControl @ foundry.js:26588
(anonymous) @ foundry.js:26479
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
async function (async)
_onCombatantControl @ foundry.js:26588
(anonymous) @ foundry.js:26479
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

This is the error that I get.

**Comment by ImaginaryfriendOnline** [comment]
In createRollInitiativeReplacement.js line 13:
`    if (isNewerVersion(game.data.version, "0.7.9")) {`
Replace 0.7.9 with 0.7.10

**Comment by ckdragons** [comment]
Will this be fixed with 7.10 or wait until 8.x is released?

**Comment by apoapostolov** [comment]
I confirm on this issue. Initiative cannot be rolled with this mod as of 0.7.10

**Comment by sfuqua** [comment]
I'll get this fixed today! I was not expecting an update to the 0.7.x line or I would've had a more robust version check.

**Comment by sfuqua** [comment]
This is resolved in 1.0.2 which I just published. The module should now be happy with 0.7.10 as well as 0.8.6. Thank you for the report!
