### ISSUE TITLE
Duplicate UI elements

### ISSUE THREAD

**Issue by iamrpgdm** [sfuqua/fvtt-hidden-initiative#6]
Looks like there's a conflict with Combat Utility Belt, Turn Alert, and Combat Enhancements causing them to show their UI twice. The previous fix doesn't seem to work.

FVTT 0.7.9
DnD5E 1.2.4

![image](https://user-images.githubusercontent.com/33824743/107161171-28f33c80-6958-11eb-9349-9ff627e6944b.png)

**Comment by sfuqua** [comment]
Apologies I missed this issue when it was first opened. Are you only seeing this issue when hidden-initiative is enabled? I am testing with Turn Alert right now on 0.8.5 and do not see any duplication. 

I switched back to 0.7.9 and tested with all of the addons mentioned and do not see any duplication:
![image](https://user-images.githubusercontent.com/6938270/119250468-23abad80-bb55-11eb-9027-638c9ac4e37e.png)

Can you confirm you're running the latest version of hidden-initiative?
